[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.gunicorn"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn wsgi:app"